version: "3"
services:
  nginx:
    build:
      context: ./eportfolio # Use the Dockerfile in the 'eportfolio' directory for the frontend
    networks:
      - portfolionetwork
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80" # Forward port 80 on the host to port 80 on the container
      - "443:443" # Forward port 443 on the host to port 443 on the container
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  backend:
    build:
      context: ./apiPortfolio
    networks:
      - portfolionetwork

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    


networks:
  portfolionetwork:
    driver: bridge
