version: "3"
services:
  nginx:
    build:
      context: ./eportfolio # Use the Dockerfile in the 'eportfolio' directory for the frontend
    networks:
      - portfolionetwork
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80" # Forward port 80 on the host to port 80 on the container
      - "443:443" # Forward port 443 on the host to port 443 on the container
    

  backend:
    build:
      context: ./apiPortfolio
    networks:
      - portfolionetwork

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: ""  # Set entrypoint to an empty string to override the default entrypoint and allow manual commands
    command: certonly --webroot --webroot-path=/var/www/certbot --agree-tos --non-interactive --email your-email@example.com -d dionfrancois.com -d www.dionfrancois.com

  
    


networks:
  portfolionetwork:
    driver: bridge
