version: "3"
services:
  nginx:
    build:
      context: ./eportfolio # Use the Dockerfile in the 'eportfolio' directory for the frontend
    networks:
      - portfolionetwork
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
      - "80:80" # Forward port 80 on the host to port 80 on the container
      - "443:443" # Forward port 443 on the host to port 443 on the container
    

  backend:
    build:
      context: ./apiPortfolio
    networks:
      - portfolionetwork

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  
    


networks:
  portfolionetwork:
    driver: bridge
