version: "3"
services:
  frontend:
    build:
      context: ./eportfolio
    networks:
      - portfolionetwork
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot-webroot:/var/www/certbot
    depends_on:
      - backend
      - certbot


  backend:
    build:
      context: ./apiPortfolio
    networks:
      - portfolionetwork

  certbot:
    image: certbot/certbot
    networks:
      - portfolionetwork
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot-webroot:/var/www/certbot

networks:
  portfolionetwork:
    driver: bridge
