version: "3"
services:
  frontend:
    build:
      context: ./eportfolio
    networks:
      - portfolionetwork
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot-webroot:/var/www/certbot
    environment:
      - SSL_CERT_PATH=/etc/letsencrypt/live/dionfrancois.com/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/dionfrancois.com/privkey.pem

  backend:
    build:
      context: ./apiPortfolio
    networks:
      - portfolionetwork

  certbot:
    image: certbot/certbot
    networks:
      - portfolionetwork
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot-webroot:/var/www/certbot

networks:
  portfolionetwork:
    driver: bridge
