version: "3"
services:
  frontend:
    build:
      context: ./eportfolio
    networks:
      - portfolionetwork
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www/:/var/www/certbot/:ro
    depends_on:
      - backend
      - certbot


  backend:
    build:
      context: ./apiPortfolio
    networks:
      - portfolionetwork

  certbot:
    image: certbot/certbot
    networks:
      - portfolionetwork
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    command: certonly --webroot -w /var/www/certbot -d dionfrancois.com

networks:
  portfolionetwork:
    driver: bridge
