version: "3"
services:
  frontend:
    build:
      context: ./eportfolio
    networks:
      - portfolionetwork
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend

  backend:
    build:
      context: ./apiPortfolio
    networks:
      - portfolionetwork
      #

  certbot:
    image: certbot/certbot:
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
networks:
  portfolionetwork:
    driver: bridge
