name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Sync code to EC2
        run: |
          rsync -avz ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:~/

      - name: Pull and run Docker Compose
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          cd ~/
          echo "Pulling down existing containers..."
          docker-compose down
          echo "Building and starting containers..."
          docker-compose -f docker-compose.yml up -d --build
          EOF
