name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Sync code to EC2
        run: |
          rsync -avz ./ {{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:~/myapp/
      - name: Pull and run Docker Compose
        run: |
          ssh ec2-user@${{ secrets.HOST_DNS }} << 'EOF'
          cd /path/to/deploy/directory
          docker-compose down
          docker-compose -f docker-compose.yml up -d --build
          EOF
