name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Print working directory on runner
        run: |
          echo "Current path on runner:"
          pwd
          ls -la  # List files in the current directory on the runner

      - name: Sync code to EC2
        run: |
          echo "Attempting to sync files..."
          rsync -avz ./ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:~/

      - name: Pull and run Docker Compose
        run: |
          ssh ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }} << 'EOF'
          set -x  # Enable command echoing
          echo "Current path before cd on EC2:"
          pwd  # Show current path on EC2
          cd ~/myapp  # Change to your app directory
          echo "Current path after cd on EC2:"
          pwd  # Show current path after changing directory
          docker-compose down
          docker-compose -f docker-compose.yml up -d --build
          EOF
